<a href="https://colab.research.google.com/github/TonyKimisintheHouse/Self-Study-ML-Fundamentals-and-DL/blob/master/practice/Practice0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Softmax Regression and Stochastiic Gradient Descent

This work is based on [Hommework 0, Question 8](https://www.cc.gatech.edu/classes/AY2018/cs7643_fall/hw0-q8/)
 of CS 7643 Deep Learning, Fall 2017. 

In [0]:
import numpy as np
import matplotlib.pyplot as plt

## Getting comfortable with Python

This work is based on [CS 231n Python Tutorial](http://cs231n.github.io/python-numpy-tutorial/)

#### Numbers
Like most languages, Python has a number of basic types including integers, floats, boleans, and strings. 

In [7]:
x = 3
print(type(x))
print(x)
print(x + 1)
print(x - 1)
print(x * 2)
print(x ** 2)
x += 1 # Note: Python does not have unary increment x++ or decrement x-- operators
print(x)
x *= 2
print(x)
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


#### Booleans
Python also implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc)

In [8]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t != f)

<class 'bool'>
False
True
False
True


#### Strings
Python also implements strings

In [10]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world #string concatenation
print(hw)
stringFormatting = '%s %s %d' % (hello, world, 12)
print(stringFormatting)

hello
5
hello world
hello world 12


In [17]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world'.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### Containers

Like other languages, Python also comes with built-in container types: list, dictionaries, sets, and tuples


#### List

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [18]:
xs = [3, 1, 2]
print(xs, xs[2])
print(xs[-1])
xs[2] = 'foo'
print(xs)
xs.append('bar')
print(xs)
x = xs.pop()
print(x, xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


which comes with helpful methods

In [20]:
# Slicing

nums = list(range(5))
print(nums) # Prints the entire list
print(nums[2:4]) # Prints a slice from index 2 to 4
print(nums[2:]) # Prints a slice from index 2 to the end
print(nums[:2]) # Prints a slice from the start to index 2 (exclusive)
print(nums[:]) # Prints a slice of the whole list
print(nums[:-1]) # Prints a slice from the start to the last (exclusive)
nums[2:4] = [8, 9] # Replaces slice from index 2 to 3 with [8, 9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [25]:
# Loops

animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)

cat
dog
monkey


`enumerate` allows accessing the index of each element within the body of a loop

In [29]:
animals = ['cat', 'dog', 'monkey']
for idx, animmal in enumerate(animals):
  print('#%d: %s' % (idx + 1, animal))

#1: monkey
#2: monkey
#3: monkey


In [33]:
# List commprehensions
# Example - Compute square number
nums = [ 0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x ** 2)
print(squares)

## We can simplify the code to
squares2 = [x ** 2 for x in nums]
print(squares2)


# we can also add conditions to list comprehension
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


#### Dictionaries 

In [36]:
d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d['fish'])
print(d.get('monkey', 'N/A'))
print(d.get('fish', 'N/A'))
del d['fish'] # removes an element from the list
print(d.get('fish', 'N/A'))

cute
True
wet
N/A
wet
N/A


In [41]:
# Like lists, you can loop through a dictionary
## by iterating over the keys
d = {'person': 2, 'cat': 4, 'spider': 8}

print('Iterating over the keys')
for animal in d:
  legs = d[animal]
  print('A %s has %d legs' % (animal, legs))
print('')
## or by iterating both keys and their corresponding values
print("Iterating both keys and their corresponding values")
for animal, legs in d.items():
  print('A %s has %d legs' % (animal, legs))

Iterating over the keys
A person has 2 legs
A cat has 4 legs
A spider has 8 legs

Iterating both keys and their corresponding values
A person has 2 legs
A cat has 4 legs
A spider has 8 legs


#### Tuples

A tuple is an immutable ordered list of values. Unlike a string, it can be used as a string for dictionaries because it is immutable

In [42]:
d = {(i, i + 1): i for i in range(10)}
t = (5, 6)
print(type(t))
print(d[t])
print(d[(1, 2)])

<class 'tuple'>
5
1


### Functions

In [48]:
def fibonacci(x):
  if x == 0:
    return 0
  if x == 1:
    return 1
  return (fibonacci(x - 1) + fibonacci(x - 2))

print(fibonacci(1))
print(fibonacci(8))

1
21


## Classes

In [53]:
class musicLover(object):
  # Constructor
  def __init__(self, name, favorite_musician):
    self.name = name
    self.favorite_musician = favorite_musician

  def greet(self, secretly_in_love=False):
    if secretly_in_love:
      print ("Hello! My name is %s" % self.name)
    else:
      print("My name is %s and I LOVE %s" % (self.name, self.favorite_musician))

Tony = musicLover('Tony', 'Coldplay')
Tony.greet()
Tony.greet(secretly_in_love=True)

My name is Tony and I LOVE Coldplay
Hello! My name is Tony


## Getting comfortable with NumPy

NumPy is a core library for high-performance multidimensional array objects, and tools for working with these arrays

In [54]:
a = np.array([1, 2, 3]) # Creates a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2]) 
a[0] = 5
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


There are functions for creating arrays

In [61]:
import numpy as np

a = np.zeros((2, 2)) # creates an array of all zeros
print(a)

b = np.ones((1, 2)) # creates an array of all ones
print(b)

c = np.full((2, 2), 7) # creates a constant array
print(c)

d = np.eye(5) # creates an identity matrix
print(d)

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.89719322 0.57722102]
 [0.54455139 0.07794357]]


Here are several ways to index into arrays

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1: 3] # slicing

print(a)
print(b)

print(b[0, 1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
3


In [70]:
row_r0 = a[1, :] # mixing integer indexing with slices yields an array of lower ranks
row_r1 = a[1:2, ] # This yields an array of the same rank as the original array

print(row_r0, row_r0.shape)
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


**Integer array indexing**

In [74]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


which allows us to use a trick that makes selecting or mutating one element from each row of a matrix

In [76]:

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**

In [78]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx)

# construct a rank 1 array that consist of the elements of a corresponding to the True values of bool idx
print(a[bool_idx])

# We can do all of the above in a single concise statement
print(a[a > 2])


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Array math

In [88]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y) # Note: This is an elementwise product. NOT MATRIX MULTIPLICATION
print(np.multiply(x, y))

print(x / y) # Likewise, this is an elementwise division
print(np.divide(x, y))

print(np.sqrt(x)) # Elementwise squareroot

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In order to do matrix multiplication, you need to use `.dot` or `np.dot(x, y)`

In [95]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(x.dot(v)) # or print(np.dot(x, v))

print(v.dot(v))

print(np.dot(x, y))

[29 67]
181
[[19 22]
 [43 50]]


In [97]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]


You can also transpose a matrix by simply using `T` attribute of an array object

In [99]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

v = np.array([1, 2, 3])
print(v)
print(v.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
