<a href="https://colab.research.google.com/github/TonyKimisintheHouse/Self-Study-ML-Fundamentals-and-DL/blob/master/notes/Getting_Started_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with PyTorch

In [0]:
import torch

## Creating tensors on PyTorch

In [9]:
print(torch.cuda.is_available())
print(torch.rand(2,2,))

x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

False
tensor([[0.9022, 0.7105],
        [0.2474, 0.1506]])


tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [0]:
x[0][0] = 5

In [11]:
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [13]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

## Tensor operations

In [26]:
random_tensor = torch.rand(2,2)
print(random_tensor)
print(random_tensor.max())
print(random_tensor.argmax())

tensor([[0.1580, 0.7473],
        [0.3705, 0.3033]])
tensor(0.7473)
tensor(1)


In [28]:
# converting type of tensor to float
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [35]:
"""
If you want to save it some memory, you can use in-place function that has the
same name but with an underscore (_)
"""
random_tensor = torch.rand(2,2)
print(random_tensor)
print(random_tensor.log2_()) # instead of random_tensor.log2
print(random_tensor)

tensor([[0.3539, 0.3154],
        [0.1040, 0.5104]])
tensor([[-1.4985, -1.6645],
        [-3.2653, -0.9703]])
tensor([[-1.4985, -1.6645],
        [-3.2653, -0.9703]])


In [39]:
"""
We can reshape a tensor. This often happens because your neural network layer may
require a slightly different input shape than what you currently have to feed into it.

USe view() or reshape()
"""

flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28) # or reshape(1,28,28)
print(viewed_tensor.shape)

torch.Size([1, 28, 28])


In [41]:
"""
You can also easily rearrange the dimensions of a tensor using permute()
"""

hwc_tensor = torch.rand(640,480,3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])